POST {{api_url}}/datapull/request/1d59ee2c-eb75-4556-89ff-6c01c4962e4a
Accept: */*
Content-Type: text/plain

PREFIX Event: <https://ontology.tno.nl/logistics/federated/Event#>
PREFIX dt: <https://ontology.tno.nl/logistics/federated/DigitalTwin#>
select ?weight where {
	?s a Event:Event .
    ?s Event:involvesDigitalTwin ?o .
    ?o dt:grossMass ?weight .
    FILTER regex (str(?s), "1d59ee2c-eb75-4556-89ff-6c01c4962e4a")
}

###