CREATE TABLE IF NOT EXISTS WEBHOOK
(
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID    VARCHAR(256)  NOT NULL,
    EVENT_TYPE   VARCHAR(256)  NOT NULL,
    CALLBACK_URL VARCHAR(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENT_TYPE
(
    ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_TYPE VARCHAR(256)           NOT NULL,
    RML        CHARACTER LARGE OBJECT NOT NULL,
    SHACL      CHARACTER LARGE OBJECT
);

CREATE UNIQUE INDEX IF NOT EXISTS EVENT_TYPE_IDX ON EVENT_TYPE (EVENT_TYPE);
