CREATE SCHEMA IF NOT EXISTS FEDERATED;
SET SCHEMA FEDERATED;
CREATE TABLE IF NOT EXISTS WEBHOOK (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID VARCHAR(200) NOT NULL,
    EVENT_TYPE VARCHAR(100) NOT NULL,
    CALLBACK_URL VARCHAR(400) NOT NULL
);