CREATE TABLE IF NOT EXISTS WEBHOOK
(
    ID                          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID                   VARCHAR(256)  NOT NULL,
    EVENT_TYPE                  VARCHAR(256)  NOT NULL,
    CALLBACK_URL                VARCHAR(1024) NOT NULL,
    USE_AUTHENTICATION          BOOLEAN  DEFAULT FALSE,
    TOKEN_URL                   VARCHAR(1024) ,
    REFRESH_URL                 VARCHAR(1024),
    AUD                         VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS EVENT_TYPE
(
    ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_TYPE        VARCHAR(256)           NOT NULL,
    RML               CHARACTER LARGE OBJECT NOT NULL,
    SHACL             CHARACTER LARGE OBJECT,
    SCHEMA_DEFINITION CHARACTER LARGE OBJECT
);

CREATE TABLE IF NOT EXISTS EVENT_DISTRIBUTION_RULE
(
    ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RULE_TYPE         VARCHAR(256)           NOT NULL,
    DESTINATIONS      VARCHAR(4096)
);

CREATE UNIQUE INDEX IF NOT EXISTS EVENT_TYPE_IDX ON EVENT_TYPE (EVENT_TYPE);

CREATE TABLE IF NOT EXISTS USERS
(
    ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME          VARCHAR(256)     NOT NULL,
    ENCRYPTEDPASSWORD VARCHAR(4096)    NOT NULL,
    ROLES             VARCHAR(4096)    NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS USERS_IDX ON USERS (USERNAME);
